### ISSUE TITLE
TypeError: can't pickle open3d.cpu.pybind.visualization.SelectionPolygonVolume objects

### ISSUE THREAD

**Issue by Qiuyanghang** [ztsrxh/RoadBEV#1]
当我调用test.py测试是否能跑通模型时，报错TypeError: can't pickle open3d.cpu.pybind.visualization.SelectionPolygonVolume objects，请问怎么解决？十分感谢回复。

**Comment by ztsrxh** [comment]
你好：
    可以提供详细的报错信息吗？训练时有没有报错？open3d库是否安装？

**Comment by Qiuyanghang** [comment]
你好：
十分感谢回复！
open3d是安装了的，训练时候也报错了，没有训练起来：
trining RoadBEV-stereo!
dataset size - train:1210, test371
num params: 7444226
Downloading: "https://download.pytorch.org/models/efficientnet_b6_lukemelas-c76e70fd.pth" to C:\Users\TODA_2/.cache\torch\hub\checkpoints\efficientnet_b6_lukemelas-c76e70fd.pth
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 165M/165M [01:11<00:00, 2.44MB/s]
logging dir: ./checkpoints/20240415012936
  0%|                                                                                                                                                                                                       | 0/50 [00:00<?, ?it/s]
Traceback (most recent call last):      
  File "train.py", line 175, in <module>
    train()
  File "train.py", line 26, in train    
    for i, sample in enumerate(train_loader):
  File "C:\Anaconda\envs\roadbev\lib\site-packages\torch\utils\data\dataloader.py", line 359, in __iter__
    return self._get_iterator()
  File "C:\Anaconda\envs\roadbev\lib\site-packages\torch\utils\data\dataloader.py", line 305, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "C:\Anaconda\envs\roadbev\lib\site-packages\torch\utils\data\dataloader.py", line 918, in __init__
    w.start()
  File "C:\Anaconda\envs\roadbev\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "C:\Anaconda\envs\roadbev\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Anaconda\envs\roadbev\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Anaconda\envs\roadbev\lib\multiprocessing\popen_spawn_win32.py", line 89, in __init__
  File "C:\Anaconda\envs\roadbev\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: can't pickle open3d.cpu.pybind.visualization.SelectionPolygonVolume objects
(roadbev) PS C:\qyh\road_reconstrcution\RoadBEV-main> Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Anaconda\envs\roadbev\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Anaconda\envs\roadbev\lib\multiprocessing\spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input

在Windows系统下的conda的环境信息为：
python 3.7.16
pillow 9.2.0
pytorch 1.10.0
torchaudio 0.10.0
torchvision 0.11.0
open3d 0.11.2 
numpy 1.21.6
opencv-python 4.9.0.80

**Comment by ztsrxh** [comment]
The open3d version is 0.16.0 in my environment. Problems originated from the pre-processed GT labels, please check whether the GT generation works well.

**Comment by Qiuyanghang** [comment]
> The open3d version is 0.16.0 in my environment. Problems originated from the pre-processed GT labels, please check whether the GT generation works well.

好的，谢谢！Thank you so much！

**Comment by ztsrxh** [comment]
We have provided the GT labels generated in our environment. You can use it and check if problems still exist.

**Comment by jiajigiser** [comment]
I have also encountered the same error mentioned above. 

My environment is :
Python 3.8.17
pytorch 1.10.0
torchaudio 0.10.0
torchvision 0.11.0

My error  message in test.py:
Testing RoadBEV-mono!
test set: 371
num params: 26646334
loading model C:\Users\16076\Desktop\2-coding\1-picture_process\RoadBEV-main\RoabBEV-mono.ckpt
Traceback (most recent call last):
  File ".\test.py", line 92, in <module>
    [metric_all, metric_depthwise] = test_sample(test_loader)
  File "C:\Users\16076\Desktop\2-coding\1-picture_process\RoadBEV-main\utils\experiment.py", line 30, in wrapper
    ret = func(*f_args, **f_kwargs)
  File ".\test.py", line 26, in test_sample
    for i, sample in enumerate(test_loader):
  File "C:\ProgramData\Anaconda3\envs\blend\lib\site-packages\torch\utils\data\dataloader.py", line 359, in __iter__
    return self._get_iterator()
  File "C:\ProgramData\Anaconda3\envs\blend\lib\site-packages\torch\utils\data\dataloader.py", line 305, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "C:\ProgramData\Anaconda3\envs\blend\lib\site-packages\torch\utils\data\dataloader.py", line 918, in __init__
    w.start()
  File "C:\ProgramData\Anaconda3\envs\blend\lib\multiprocessing\process.py", line 121, in start   
    self._popen = self._Popen(self)
  File "C:\ProgramData\Anaconda3\envs\blend\lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\ProgramData\Anaconda3\envs\blend\lib\multiprocessing\context.py", line 327, in _Popen
    return Popen(process_obj)
  File "C:\ProgramData\Anaconda3\envs\blend\lib\multiprocessing\popen_spawn_win32.py", line 93, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\ProgramData\Anaconda3\envs\blend\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: cannot pickle 'open3d.cpu.pybind.visualization.SelectionPolygonVolume' object

My error  message in train.py:
(blend) PS C:\Users\16076\Desktop\2-coding\1-picture_process\RoadBEV-main> python .\train.py --lr 8e-4       
trining RoadBEV-mono!
dataset size - train:1210, test371
num params: 26646334
logging dir: ./checkpoints/20240418115722
  0%|                                                                                                                                                                                                           | 0/50 [00:02<?, ?it/s]Traceback (most recent call last):

  File "C:\ProgramData\Anaconda3\envs\blend\lib\site-packages\torch\utils\data\dataloader.py", line 359, in __iter__
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input
    return self._get_iterator()
  File "C:\ProgramData\Anaconda3\envs\blend\lib\site-packages\torch\utils\data\dataloader.py", line 305, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "C:\ProgramData\Anaconda3\envs\blend\lib\site-packages\torch\utils\data\dataloader.py", line 918, in __init__
    w.start()
  File "C:\ProgramData\Anaconda3\envs\blend\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "C:\ProgramData\Anaconda3\envs\blend\lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\ProgramData\Anaconda3\envs\blend\lib\multiprocessing\context.py", line 327, in _Popen
    return Popen(process_obj)
  File "C:\ProgramData\Anaconda3\envs\blend\lib\multiprocessing\popen_spawn_win32.py", line 93, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\ProgramData\Anaconda3\envs\blend\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: cannot pickle 'open3d.cpu.pybind.visualization.SelectionPolygonVolume' object

 My question:May I ask if different versions of Python may be the reason for the Open3D error?

**Comment by ztsrxh** [comment]
> I have also encountered the same error mentioned above.
> 
> My environment is : Python 3.8.17 pytorch 1.10.0 torchaudio 0.10.0 torchvision 0.11.0
> 
> My error message in test.py: Testing RoadBEV-mono! test set: 371 num params: 26646334 loading model C:\Users\16076\Desktop\2-coding\1-picture_process\RoadBEV-main\RoabBEV-mono.ckpt Traceback (most recent call last): File ".\test.py", line 92, in [metric_all, metric_depthwise] = test_sample(test_loader) File "C:\Users\16076\Desktop\2-coding\1-picture_process\RoadBEV-main\utils\experiment.py", line 30, in wrapper ret = func(*f_args, **f_kwargs) File ".\test.py", line 26, in test_sample for i, sample in enumerate(test_loader): File "C:\ProgramData\Anaconda3\envs\blend\lib\site-packages\torch\utils\data\dataloader.py", line 359, in **iter** return self._get_iterator() File "C:\ProgramData\Anaconda3\envs\blend\lib\site-packages\torch\utils\data\dataloader.py", line 305, in _get_iterator return _MultiProcessingDataLoaderIter(self) File "C:\ProgramData\Anaconda3\envs\blend\lib\site-packages\torch\utils\data\dataloader.py", line 918, in **init** w.start() File "C:\ProgramData\Anaconda3\envs\blend\lib\multiprocessing\process.py", line 121, in start self._popen = self._Popen(self) File "C:\ProgramData\Anaconda3\envs\blend\lib\multiprocessing\context.py", line 224, in _Popen return _default_context.get_context().Process._Popen(process_obj) File "C:\ProgramData\Anaconda3\envs\blend\lib\multiprocessing\context.py", line 327, in _Popen return Popen(process_obj) File "C:\ProgramData\Anaconda3\envs\blend\lib\multiprocessing\popen_spawn_win32.py", line 93, in **init** reduction.dump(process_obj, to_child) File "C:\ProgramData\Anaconda3\envs\blend\lib\multiprocessing\reduction.py", line 60, in dump ForkingPickler(file, protocol).dump(obj) TypeError: cannot pickle 'open3d.cpu.pybind.visualization.SelectionPolygonVolume' object
> 
> My error message in train.py: (blend) PS C:\Users\16076\Desktop\2-coding\1-picture_process\RoadBEV-main> python .\train.py --lr 8e-4 trining RoadBEV-mono! dataset size - train:1210, test371 num params: 26646334 logging dir: ./checkpoints/20240418115722 0%| | 0/50 [00:02<?, ?it/s]Traceback (most recent call last):
> 
> File "C:\ProgramData\Anaconda3\envs\blend\lib\site-packages\torch\utils\data\dataloader.py", line 359, in **iter** self = reduction.pickle.load(from_parent) EOFError: Ran out of input return self._get_iterator() File "C:\ProgramData\Anaconda3\envs\blend\lib\site-packages\torch\utils\data\dataloader.py", line 305, in _get_iterator return _MultiProcessingDataLoaderIter(self) File "C:\ProgramData\Anaconda3\envs\blend\lib\site-packages\torch\utils\data\dataloader.py", line 918, in **init** w.start() File "C:\ProgramData\Anaconda3\envs\blend\lib\multiprocessing\process.py", line 121, in start self._popen = self._Popen(self) File "C:\ProgramData\Anaconda3\envs\blend\lib\multiprocessing\context.py", line 224, in _Popen return _default_context.get_context().Process._Popen(process_obj) File "C:\ProgramData\Anaconda3\envs\blend\lib\multiprocessing\context.py", line 327, in _Popen return Popen(process_obj) File "C:\ProgramData\Anaconda3\envs\blend\lib\multiprocessing\popen_spawn_win32.py", line 93, in **init** reduction.dump(process_obj, to_child) File "C:\ProgramData\Anaconda3\envs\blend\lib\multiprocessing\reduction.py", line 60, in dump ForkingPickler(file, protocol).dump(obj) TypeError: cannot pickle 'open3d.cpu.pybind.visualization.SelectionPolygonVolume' object
> 
> My question:May I ask if different versions of Python may be the reason for the Open3D error?

Hi, we have not encountered this problem in our environment. You can first use the GT files we provided. Can you give me a sample _.pkl_ GT file generated in your environment? Thanks!

**Comment by ztsrxh** [comment]
> (RoadBEV) D:\RoadBEV-main>python train.py --lr 8e-4 trining RoadBEV-mono! dataset size - train:1210, test371 num params: 26646334 logging dir: ./checkpoints/20240419150246 0%| | 0/50 [00:03<?, ?it/s] Traceback (most recent call last): Traceback (most recent call last): File "", line 1, in File "train.py", line 175, in train() File "train.py", line 26, in train File "C:\Users\liush\anaconda3\envs\RoadBEV\lib\multiprocessing\spawn.py", line 116, in spawn_main for i, sample in enumerate(train_loader): File "C:\Users\liush\anaconda3\envs\RoadBEV\lib\site-packages\torch\utils\data\dataloader.py", line 439, in **iter** exitcode = _main(fd, parent_sentinel) File "C:\Users\liush\anaconda3\envs\RoadBEV\lib\multiprocessing\spawn.py", line 126, in _main self = reduction.pickle.load(from_parent) EOFError: Ran out of input return self._get_iterator() File "C:\Users\liush\anaconda3\envs\RoadBEV\lib\site-packages\torch\utils\data\dataloader.py", line 387, in _get_iterator return _MultiProcessingDataLoaderIter(self) File "C:\Users\liush\anaconda3\envs\RoadBEV\lib\site-packages\torch\utils\data\dataloader.py", line 1040, in **init** w.start() File "C:\Users\liush\anaconda3\envs\RoadBEV\lib\multiprocessing\process.py", line 121, in start self._popen = self._Popen(self) File "C:\Users\liush\anaconda3\envs\RoadBEV\lib\multiprocessing\context.py", line 224, in _Popen return _default_context.get_context().Process._Popen(process_obj) File "C:\Users\liush\anaconda3\envs\RoadBEV\lib\multiprocessing\context.py", line 327, in _Popen return Popen(process_obj) File "C:\Users\liush\anaconda3\envs\RoadBEV\lib\multiprocessing\popen_spawn_win32.py", line 93, in **init** reduction.dump(process_obj, to_child) File "C:\Users\liush\anaconda3\envs\RoadBEV\lib\multiprocessing\reduction.py", line 60, in dump ForkingPickler(file, protocol).dump(obj) TypeError: cannot pickle 'open3d.cpu.pybind.visualization.SelectionPolygonVolume' object
> 
> 同样的报错。另，能列出详细的目录和文件结构吗？谢谢

Could you please give me a copy of your current codes? my email zhaot20@berkeley.edu

**Comment by liushuquan2022** [comment]
Tong Zhao：

您好！感谢您的关注，代码如附件。

1）工作环境如下：
conda create -n   RoadBEV  python=3.8 -y
conda activate RoadBEV
conda install pytorch==2.2.0 torchvision==0.17.0 torchaudio==2.2.0 pytorch-cuda=12.1 -c pytorch -c nvidia
conda install -c open3d-admin open3d
pip install opencv-python
pip install pillow
pip install matplotlib
pip install tqdm

为方便起见，附件中已包含 requirements.txt 文件。

2）项目文件结构如下：

RoadBEV-main
├── utils
│   └── dataset.py
├── filenames
│   ├── train
│   │    ├── 20230317074852.000.pkl
│   │    └── ...
│   ├── test
│   │    ├── 20230317075641.200.pkl
│   │    └── ...
├── train.py
├── test.py
└── preprocess_gt.py
│
│
│
├── dataset
│   ├── RSRD-dense
│   │    ├── train
│   │    │       ├── 2023-03-17-07-48-37
│   │    │       └── ...
│   │    └── test
│   │             ├── depth
│   │             └── depth_half
│   │             └── disparity
│   │             └── disparity_half
│   │             └── left
│   │             └── left_half
│   │             └── pcd
│   │             └── right
│   │             └── right_half
│   │
│   ├── preprocessed
│   │    ├── train
│   │    │       ├── 20230317074850.000.pkl
│   │    │       └── ...
│   │    └── test
│   │             ├── 20230317075641.200.pkl
│   │             └── ...
│   ├── RSRD_calib
│   │    ├── calib_20230317.pkl
│   │    ├── calib_20230317_half.pkl
│   │    └── ...



liushuquan


***@***.***
 
From: Tong Zhao
Date: 2024-04-20 02:40
To: ztsrxh/RoadBEV
CC: liushuquan2022; Comment
Subject: Re: [ztsrxh/RoadBEV] TypeError: can't pickle open3d.cpu.pybind.visualization.SelectionPolygonVolume objects (Issue #1)
(RoadBEV) D:\RoadBEV-main>python train.py --lr 8e-4 trining RoadBEV-mono! dataset size - train:1210, test371 num params: 26646334 logging dir: ./checkpoints/20240419150246 0%| | 0/50 [00:03<?, ?it/s] Traceback (most recent call last): Traceback (most recent call last): File "", line 1, in File "train.py", line 175, in train() File "train.py", line 26, in train File "C:\Users\liush\anaconda3\envs\RoadBEV\lib\multiprocessing\spawn.py", line 116, in spawn_main for i, sample in enumerate(train_loader): File "C:\Users\liush\anaconda3\envs\RoadBEV\lib\site-packages\torch\utils\data\dataloader.py", line 439, in iter exitcode = _main(fd, parent_sentinel) File "C:\Users\liush\anaconda3\envs\RoadBEV\lib\multiprocessing\spawn.py", line 126, in _main self = reduction.pickle.load(from_parent) EOFError: Ran out of input return self._get_iterator() File "C:\Users\liush\anaconda3\envs\RoadBEV\lib\site-packages\torch\utils\data\dataloader.py", line 387, in _get_iterator return _MultiProcessingDataLoaderIter(self) File "C:\Users\liush\anaconda3\envs\RoadBEV\lib\site-packages\torch\utils\data\dataloader.py", line 1040, in init w.start() File "C:\Users\liush\anaconda3\envs\RoadBEV\lib\multiprocessing\process.py", line 121, in start self._popen = self._Popen(self) File "C:\Users\liush\anaconda3\envs\RoadBEV\lib\multiprocessing\context.py", line 224, in _Popen return _default_context.get_context().Process._Popen(process_obj) File "C:\Users\liush\anaconda3\envs\RoadBEV\lib\multiprocessing\context.py", line 327, in _Popen return Popen(process_obj) File "C:\Users\liush\anaconda3\envs\RoadBEV\lib\multiprocessing\popen_spawn_win32.py", line 93, in init reduction.dump(process_obj, to_child) File "C:\Users\liush\anaconda3\envs\RoadBEV\lib\multiprocessing\reduction.py", line 60, in dump ForkingPickler(file, protocol).dump(obj) TypeError: cannot pickle 'open3d.cpu.pybind.visualization.SelectionPolygonVolume' object
同样的报错。另，能列出详细的目录和文件结构吗？谢谢
Could you please give me a copy of your current codes? my email ***@***.***
―
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you commented.Message ID: ***@***.***>


-----------------------------------------------------------
以下文件通过foxmail发给您。保存时间有限制，请及时提取。
RoadBEV-main.zip (305.4 M) (有效时间到: 2024/5/20 11:49:10)
链接: https://exmail.qq.com/cgi-bin/ftnExs_download?k=71356333dd9b8cdecf20a21e1362530016505b06055254025a185a0a0d5749060954001e5601000a1451550a030350540a505707006274326b5a02577627321f54540a5d1a180d42390b1764&t=exs_ftn_download&code=95c34bd2

**Comment by ztsrxh** [comment]
> EOFError: Ran out of input

Could you please add my wechat 微信？I need more information to localize the bug. My number: Mr-Tongski

**Comment by ztsrxh** [comment]
> Tong Zhao： 您好！感谢您的关注，代码如附件。 1）工作环境如下： conda create -n RoadBEV python=3.8 -y conda activate RoadBEV conda install pytorch==2.2.0 torchvision==0.17.0 torchaudio==2.2.0 pytorch-cuda=12.1 -c pytorch -c nvidia conda install -c open3d-admin open3d pip install opencv-python pip install pillow pip install matplotlib pip install tqdm 为方便起见，附件中已包含 requirements.txt 文件。 2）项目文件结构如下： RoadBEV-main ├── utils │ └── dataset.py ├── filenames │ ├── train │ │ ├── 20230317074852.000.pkl │ │ └── ... │ ├── test │ │ ├── 20230317075641.200.pkl │ │ └── ... ├── train.py ├── test.py └── preprocess_gt.py │ │ │ ├── dataset │ ├── RSRD-dense │ │ ├── train │ │ │ ├── 2023-03-17-07-48-37 │ │ │ └── ... │ │ └── test │ │ ├── depth │ │ └── depth_half │ │ └── disparity │ │ └── disparity_half │ │ └── left │ │ └── left_half │ │ └── pcd │ │ └── right │ │ └── right_half │ │ │ ├── preprocessed │ │ ├── train │ │ │ ├── 20230317074850.000.pkl │ │ │ └── ... │ │ └── test │ │ ├── 20230317075641.200.pkl │ │ └── ... │ ├── RSRD_calib │ │ ├── calib_20230317.pkl │ │ ├── calib_20230317_half.pkl │ │ └── ... liushuquan ***@***.*** From: Tong Zhao Date: 2024-04-20 02:40 To: ztsrxh/RoadBEV CC: liushuquan2022; Comment Subject: Re: [ztsrxh/RoadBEV] TypeError: can't pickle open3d.cpu.pybind.visualization.SelectionPolygonVolume objects (Issue #1) (RoadBEV) D:\RoadBEV-main>python train.py --lr 8e-4 trining RoadBEV-mono! dataset size - train:1210, test371 num params: 26646334 logging dir: ./checkpoints/20240419150246 0%| | 0/50 [00:03<?, ?it/s] Traceback (most recent call last): Traceback (most recent call last): File "", line 1, in File "train.py", line 175, in train() File "train.py", line 26, in train File "C:\Users\liush\anaconda3\envs\RoadBEV\lib\multiprocessing\spawn.py", line 116, in spawn_main for i, sample in enumerate(train_loader): File "C:\Users\liush\anaconda3\envs\RoadBEV\lib\site-packages\torch\utils\data\dataloader.py", line 439, in iter exitcode = _main(fd, parent_sentinel) File "C:\Users\liush\anaconda3\envs\RoadBEV\lib\multiprocessing\spawn.py", line 126, in _main self = reduction.pickle.load(from_parent) EOFError: Ran out of input return self._get_iterator() File "C:\Users\liush\anaconda3\envs\RoadBEV\lib\site-packages\torch\utils\data\dataloader.py", line 387, in _get_iterator return _MultiProcessingDataLoaderIter(self) File "C:\Users\liush\anaconda3\envs\RoadBEV\lib\site-packages\torch\utils\data\dataloader.py", line 1040, in init w.start() File "C:\Users\liush\anaconda3\envs\RoadBEV\lib\multiprocessing\process.py", line 121, in start self._popen = self._Popen(self) File "C:\Users\liush\anaconda3\envs\RoadBEV\lib\multiprocessing\context.py", line 224, in _Popen return _default_context.get_context().Process._Popen(process_obj) File "C:\Users\liush\anaconda3\envs\RoadBEV\lib\multiprocessing\context.py", line 327, in _Popen return Popen(process_obj) File "C:\Users\liush\anaconda3\envs\RoadBEV\lib\multiprocessing\popen_spawn_win32.py", line 93, in init reduction.dump(process_obj, to_child) File "C:\Users\liush\anaconda3\envs\RoadBEV\lib\multiprocessing\reduction.py", line 60, in dump ForkingPickler(file, protocol).dump(obj) TypeError: cannot pickle 'open3d.cpu.pybind.visualization.SelectionPolygonVolume' object 同样的报错。另，能列出详细的目录和文件结构吗？谢谢 Could you please give me a copy of your current codes? my email ***@***.*** ― Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>
> […](#)
> ----------------------------------------------------------- 以下文件通过foxmail发给您。保存时间有限制，请及时提取。 RoadBEV-main.zip (305.4 M) (有效时间到: 2024/5/20 11:49:10) 链接: https://exmail.qq.com/cgi-bin/ftnExs_download?k=71356333dd9b8cdecf20a21e1362530016505b06055254025a185a0a0d5749060954001e5601000a1451550a030350540a505707006274326b5a02577627321f54540a5d1a180d42390b1764&t=exs_ftn_download&code=95c34bd2

Could you please add my wechat 微信？I need more information to localize the bug. My number: Mr-Tongski

**Comment by liushuquan2022** [comment]
在Tong Zhao的帮助下，已解决。非常感谢团队的贡献！

**Comment by ztsrxh** [comment]
@jiajigiser @Qiuyanghang  Hello, we have completely fixed this problem. The problem is not from versions, but that some objects of classes cannot be serialized.  You can repull the repo now. The _ckpt_ weights are also updated. We also found some mistakes in the paper, and we will update it in next days.

**Comment by jiajigiser** [comment]
> @jiajigiser @Qiuyanghang Hello, we have completely fixed this problem. The problem is not from versions, but that some objects of classes cannot be serialized. You can repull the repo now. The _ckpt_ weights are also updated. We also found some mistakes in the paper, and we will update it in next days.

Thanks! I will continue to follow your updates

**Comment by jiajigiser** [comment]
> @jiajigiser @Qiuyanghang Hello, we have completely fixed this problem. The problem is not from versions, but that some objects of classes cannot be serialized. You can repull the repo now. The _ckpt_ weights are also updated. We also found some mistakes in the paper, and we will update it in next days.
Hello, I tried to change the num__workers=0 at:
 test_loader = DataLoader(test_set, 1, shuffle=False, num_workers=0, drop_last=False, pin_memory=True)【in test.py】. 
After modifying the parameters, there were no previous errors with Open3D.
