### ISSUE TITLE
Export requirements. txt (a list of all libraries and versions)

### ISSUE THREAD

**Issue by ztsrxh** [ztsrxh/RoadBEV#4]
May I ask if it is possible to export requirements. txt (a list of all libraries and versions)? My CUDA version is 11.8, and I am not sure how to install the correct library version.

_Originally posted by @jiajigiser in https://github.com/ztsrxh/RoadBEV/issues/2#issuecomment-2065577101_

**Comment by ztsrxh** [comment]
[requirements.txt](https://github.com/ztsrxh/RoadBEV/files/15032055/requirements.txt)
Here is the full environment information. Please re-pull the repo as we have fixed some bugs just now. The _ckpt_ weights are also updated.

**Comment by jiajigiser** [comment]
> [requirements.txt](https://github.com/ztsrxh/RoadBEV/files/15032055/requirements.txt) Here is the full environment information. Please re-pull the repo as we have fixed some bugs just now. The _ckpt_ weights are also updated.

Thanks!
