### ISSUE TITLE
how to view the results of 3D reconstruction?

### ISSUE THREAD

**Issue by ztsrxh** [ztsrxh/RoadBEV#5]
May I ask how to visualize.pkl results(elevation result?) and how to view the results of 3D reconstruction?

_Originally posted by @jiajigiser in https://github.com/ztsrxh/RoadBEV/issues/2#issuecomment-2072509864_

**Comment by ztsrxh** [comment]
See _visualization.py_

**Comment by jiajigiser** [comment]
[my_testpkl.zip](https://github.com/ztsrxh/RoadBEV/files/15123677/my_testpkl.zip)
First of all, thank you for your reply and for providing visualization tools! However, both the GT. pkl generated through preprocess_gt.py and the. pkl inferred/predicted through test.py have not been successfully visualized. I want to know what format is contained within. pkl and why my. pkl results cannot be visualized. The above compressed file is a partial result saved by  running test.py

**Comment by jiajigiser** [comment]
> See _visualization.py_

[my_testpkl.zip](https://github.com/ztsrxh/RoadBEV/files/15123755/my_testpkl.zip)
First of all, thank you for your reply and for providing visualization tools! However, both the GT. pkl generated through preprocess_gt.py and the. pkl inferred/predicted through test.py have not been successfully visualized. I want to know what format is contained within. pkl and why my. pkl results cannot be visualized. The above compressed file is a partial result saved by running test.py
