### ISSUE TITLE
训练问题

### ISSUE THREAD

**Issue by 587184765231** [ztsrxh/RoadBEV#8]
这个训练完的ckpt全是一样的，模型不训练，能问下为啥会出现这种问题吗
![Q_Q72904I9WN~Y61}4RFEVT](https://github.com/ztsrxh/RoadBEV/assets/168443660/afabbc76-bc23-43db-ba7a-c292a4128598)

**Comment by ztsrxh** [comment]
你好，这是训练时保存的权重文件，请阅读代码以及补充PyTorch 基础知识。
